default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        additional_dependencies:
          ["prettier@2.5.0", "prettier-plugin-solidity@1.0.0-beta.19"]
        args: ["--plugin=prettier-plugin-solidity"]
        exclude: |
          (?x)(
              ^contracts/openzeppelin/.*|
              wasm_exec.js$
          )

        types_or:
          [
            "yaml",
            "markdown",
            "solidity",
            "makefile",
            "gitignore",
            "toml",
            "json",
            "javascript",
            "proto",
          ]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.4.1"
    hooks:
      - id: eslint

  - repo: https://github.com/shutter-network/pre-commit-go-hooks
    rev: "33e0e25bfc46fd486e16617ed5d727c0c2c3b751"
    hooks:
      - id: go-mod-tidy
        args: ["./rolling-shutter"]

      - id: gci
        args: ["-local", "github.com/shutter-network/shutter"]
        exclude: |
          (?x)(
              ^.*\.gen\.go$|
              ^rolling-shutter/shmsg/.*\.pb\.go$|
              ^rolling-shutter/shcryptowasm/.*_wasm\.go$
          )
      - id: gofumpt
        exclude: |
          (?x)(
              ^.*\.gen\.go$|
              ^rolling-shutter/shmsg/.*\.pb\.go$|
              ^rolling-shutter/shcryptowasm/.*_wasm\.go$
          )
