default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: generate
        name: generate
        language: system
        entry: bash -c 'cd rolling-shutter && make generate'
        always_run: true
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: file-contents-sorter
        files: \.tool-versions$
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        additional_dependencies:
          ["prettier@2.5.0", "prettier-plugin-solidity@1.0.0-beta.19"]
        args: ["--plugin=prettier-plugin-solidity"]
        exclude: |
          (?x)(
              ^contracts/openzeppelin/.*|
              wasm_exec.js$
          )

        types_or:
          [
            "yaml",
            "markdown",
            "solidity",
            "makefile",
            "gitignore",
            "toml",
            "json",
            "javascript",
            "proto",
          ]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.4.1"
    hooks:
      - id: eslint

  - repo: https://github.com/shutter-network/pre-commit-go-hooks
    rev: "ed735ca2048f831625cd155cf6a38b4a42d79d9b"
    hooks:
      - id: go-mod-tidy
        args: ["./rolling-shutter"]

      - id: gci
        args:
          [
            "--custom-order",
            "-sStandard",
            "-sDefault",
            "-sPrefix(github.com/shutter-network/shutter)",
            "-sPrefix(github.com/shutter-network/rolling-shutter)",
          ]
        exclude: |
          (?x)(
              ^.*\.gen\.go$|
              ^rolling-shutter/shmsg/.*\.pb\.go$|
              ^rolling-shutter/p2pmsg/.*\.pb\.go$|
              ^rolling-shutter/shcryptowasm/.*_wasm\.go$
          )
      - id: gofumpt
        exclude: |
          (?x)(
              ^.*\.gen\.go$|
              ^rolling-shutter/shmsg/.*\.pb\.go$|
              ^rolling-shutter/p2pmsg/.*\.pb\.go$|
              ^rolling-shutter/shcryptowasm/.*_wasm\.go$
          )
