default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        additional_dependencies:
          ["prettier@2.3.2", "prettier-plugin-solidity@1.0.0-beta.16"]
        args: ["--plugin=prettier-plugin-solidity"]
        exclude: "^contracts/openzeppelin/.*|wasm_exec.js$"
