version: 2.1

commands:
  install-go:
    steps:
      - run:
          name: Install go
          command: |
            curl -sSL "https://golang.org/dl/go1.17.linux-amd64.tar.gz" | sudo tar -xz -C /usr/local/
            mkdir -p ~/go/bin
            echo >${BASH_ENV} 'export PATH=/usr/local/go/bin:~/go/bin:${PATH}'

executors:
  py37:
    docker:
      - image: cimg/python:3.7.11@sha256:5280078dacde9c6093da25c5544d224483e89ac17b19404b8c348d00b7289bdf
        environment:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
  node14:
    docker:
      - image: cimg/node:14.17.4

  go:
    docker:
      - image: cimg/go:1.17
        environment:
          GO111MODULE: "on"
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
  go-integration:
    docker:
      - image: cimg/go:1.17
        environment:
          GO111MODULE: "on"
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          ROLLING_SHUTTER_TESTDB_URL: postgres://pguser:password@localhost:5432/testdb
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
  go116:
    docker:
      - image: cimg/go:1.16
        environment:
          GO111MODULE: "on"
          PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  pre-commit:
    executor: py37
    working_directory: ~/src
    steps:
      - checkout
      - install-go
      - restore_cache:
          key: pre-commit-cache-v2-{{ checksum ".pre-commit-config.yaml" }}
      - run: pip install --user pre-commit
      - run: pre-commit install-hooks
      - save_cache:
          key: pre-commit-cache-v2-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
            - ~/.local
      - run: pre-commit run --show-diff-on-failure -a

workflows:
  version: 2
  main:
    jobs:
      - pre-commit
