version: 2.1

# CircleCI dynamic configuration file, see
# https://circleci.com/docs/2.0/dynamic-config/

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

executors:
  clojure:
    docker:
      - image: clojure:openjdk-11-tools-deps-slim-buster

jobs:
  gen:
    executor: clojure
    steps:
      - run:
          name: Install curl, jq and git
          command: |
            apt-get update
            apt-get install -y curl jq git
      - checkout
      - run:
          name: Generate continuation config
          command: |
            cd .circleci
            clojure -X gen/gen :validate false :base '"origin/main"'
            cd ..
      - continuation/continue:
          configuration_path: .circleci/continue-generated.yml

workflows:
  always:
    jobs:
      - gen
