version: 2.1

# CircleCI dynamic configuration file, see
# https://circleci.com/docs/2.0/dynamic-config/

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

executors:
  cimg-base:
    docker:
      - image: cimg/base:2022.03

jobs:
  gen:
    executor: cimg-base
    working_directory: ~/src/.circleci
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          key: gen-clj-v8
      - run:
          name: Install babashka with asdf
          command: |
            if [[ -e ~/.asdf ]]; then
              echo "asdf already installed"
            else
              git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
              source ~/.asdf/asdf.sh
              asdf plugin add babashka
              asdf install babashka
            fi
            echo >${BASH_ENV} 'source ~/.asdf/asdf.sh'
      - run:
          name: Generate continuation config
          command: |
            bb -gen-ci
      - save_cache:
          key: gen-clj-v8
          paths:
            - ~/.asdf
      - continuation/continue:
          configuration_path: continue-generated.yml

workflows:
  gen:
    jobs:
      - gen:
          filters:
            tags:
              only: /^.*$/
