version: 2.1

# CircleCI dynamic configuration file, see
# https://circleci.com/docs/2.0/dynamic-config/

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

commands:
  install-asdf:
    steps:
      - run:
          name: Install asdf
          command: |
            if [[ -e ~/.asdf ]]; then
              echo "asdf already installed"
            else
              git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1
            fi
            echo >${BASH_ENV} 'source ~/.asdf/asdf.sh'

executors:
  cimg-base:
    docker:
      - image: cimg/base:2021.11

jobs:
  gen:
    executor: cimg-base
    working_directory: ~/src/.circleci
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          key: gen-clj-v4
      - install-asdf
      - run:
          name: Install babashka
          command: |
            asdf plugin add babashka || true
            asdf install babashka
      - run:
          name: Generate continuation config
          command: |
            bb -gen-ci
      - save_cache:
          key: gen-clj-v4
          paths:
            - ~/.asdf
      - continuation/continue:
          configuration_path: continue-generated.yml

workflows:
  always:
    jobs:
      - gen
