version: 2.1

orbs:
  node: circleci/node@4.6

executors:
  py37:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
  node14:
    docker:
      - image: cimg/node:14.17.4

jobs:
  pre-commit:
    executor: py37
    working_directory: ~/src
    steps:
      - checkout
      - restore_cache:
          key: pre-commit-cache-v1-{{ checksum ".pre-commit-config.yaml" }}
      - run: pip install --user pre-commit
      - run: pre-commit install-hooks
      - save_cache:
          key: pre-commit-cache-v1-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
            - ~/.local
      - run: pre-commit run --show-diff-on-failure -a

  hardhat:
    executor: node14
    working_directory: ~/src/contracts
    steps:
      - checkout:
          path: ~/src
      - node/install-packages
      - run: npx hardhat test

workflows:
  version: 2
  main:
    jobs:
      - pre-commit
      - hardhat
# Local Variables:
# compile-command: "circleci config validate"
# projectile-project-compilation-cmd: "circleci config validate"
# End:
