version: 2.1

# CircleCI dynamic configuration file, see
# https://circleci.com/docs/2.0/dynamic-config/

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

commands:
  install-clojure:
    steps:
      - run:
          name: Install clojure CLI tools
          command: |
            if [[ -e ~/clj/bin/clojure ]]; then
              echo "Clojure already installed"
            else
              curl -O https://download.clojure.org/install/linux-install-1.10.3.967.sh
              bash ./linux-install-1.10.3.967.sh --prefix ~/clj
              rm ./linux-install-1.10.3.967.sh
            fi
            echo >${BASH_ENV} 'export PATH=~/clj/bin:${PATH}'

executors:
  openjdk:
    docker:
      - image: cimg/openjdk:8.0.292

jobs:
  gen:
    executor: openjdk
    working_directory: ~/src/.circleci
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          key: gen-clj-v1-{{ checksum "deps.edn"}}
      - install-clojure
      - run:
          name: Generate continuation config
          command: |
            clojure -X gen/gen :validate false :base '"origin/main"'
      - save_cache:
          key: gen-clj-v1-{{ checksum "deps.edn"}}
          paths:
            - ~/.m2
            - ~/clj
            - .cpcache
      - continuation/continue:
          configuration_path: continue-generated.yml

workflows:
  always:
    jobs:
      - gen
