orbs:
  node: circleci/node@4.6

jobs:
  hardhat:
    executor: node14
    working_directory: ~/src/contracts
    steps:
      - checkout:
          path: ~/src
      - node/install-packages
      - run: npx hardhat test
      - run: npx hardhat deploy

workflows:
  version: 2
  contracts:
    jobs:
      - hardhat
