jobs:
  rs-generate:
    executor: go
    working_directory: ~/src/rolling-shutter
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          keys:
            - rs-generate-v3-{{ checksum "go.sum" }}-{{checksum "go.mod"}}
      - run:
          name: "Download and install protoc"
          command: |
            if [[ -e ~/bin/protoc ]]; then
              echo "protoc already installed"
            else
              curl -o /tmp/protoc.zip -sSL https://github.com/protocolbuffers/protobuf/releases/download/v3.18.0/protoc-3.18.0-linux-x86_64.zip
              unzip -d ~ /tmp/protoc.zip bin/protoc
            fi
      - run: make install-protoc-gen-go install-sqlc
      - run: make generate
      - save_cache:
          key: rs-generate-v3-{{ checksum "go.sum" }}-{{checksum "go.mod"}}
          paths:
            - "~/go/pkg/mod"
            - "~/.cache/go-build"
            - "~/bin"
      - run: git diff --exit-code

  rs-build:
    parameters:
      go-version:
        type: string
    executor: << parameters.go-version >>
    working_directory: ~/src/rolling-shutter
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}-{{ checksum "go.mod" }}
      - run: go get -d ./
      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}-{{ checksum "go.mod" }}
          paths:
            - ~/go/pkg/mod
      - restore_cache:
          keys:
            - rs-build-<< parameters.go-version >>-v2-{{ checksum "go.sum" }}-{{ checksum "go.mod" }}
      - run: make build wasm
      - run:
          name: "Run unit tests with gotestsum"
          command: |
            mkdir -p report/unit report/integration
            gotestsum -f standard-verbose --junitfile report/unit/tests.xml -- -short ./...
      - run:
          name: Wait for PostgreSQL
          command: |
            if [[ -v ROLLING_SHUTTER_TESTDB_URL ]]; then
              dockerize -wait tcp://localhost:5432 -timeout 1m
            fi
      - run:
          name: "Run integration tests with gotestsum"
          command: |
            gotestsum -f standard-verbose --junitfile report/integration/tests.xml -- -run Integration -count=1 ./...
      - store_test_results:
          path: report
      - save_cache:
          key: rs-build-<< parameters.go-version >>-v2-{{ checksum "go.sum" }}-{{ checksum "go.mod" }}
          paths:
            - "~/.cache/go-build"

  publish-release:
    executor: go
    working_directory: ~/src/rolling-shutter
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          keys:
            - rs-build-go-integration-v1-{{ checksum "go.sum" }}
      - run: env VERSION=${CIRCLE_TAG} ./build-release
      - run: go install github.com/tcnksm/ghr@v0.13.0
      - attach_workspace:
          at: ~/share
      - run:
          name: Upload binaries and combined.json
          command: |
            cp ~/share/combined.json bin/
            ghr ${CIRCLE_TAG} bin/

  rs-lint:
    executor: go
    working_directory: ~/src/rolling-shutter
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}-{{ checksum "go.mod" }}
      - restore_cache:
          keys:
            - rs-lint-v2-{{ checksum "go.sum" }}-{{ checksum "go.mod" }}
      - run:
          name: "Install golangci-lint"
          command: |
            if [[ -e ~/bin/golangci-lint ]]; then
              echo "golangci-lint already installed"
            else
              mkdir -p ~/bin
              curl -sSL -o /tmp/golangci-lint.tgz https://github.com/golangci/golangci-lint/releases/download/v1.42.1/golangci-lint-1.42.1-linux-amd64.tar.gz
              tar -C ~/bin --strip-components=1 -xf /tmp/golangci-lint.tgz
            fi
      - run: |
          make lint-changes
      - save_cache:
          key: rs-lint-v2-{{ checksum "go.sum" }}-{{ checksum "go.mod" }}
          paths:
            - "~/.cache/go-build"
            - "~/.cache/golangci-lint"
            - "~/bin/golangci-lint"
workflows:
  rolling-shutter:
    jobs:
      - rs-generate:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - rs-build:
          matrix:
            parameters:
              go-version: [go-integration, go116]
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-release:
          requires:
            - rs-build
          context:
            - upload-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - rs-lint:
          filters:
            branches:
              ignore: /main/
