jobs:
  rs-build:
    parameters:
      go-version:
        type: string
    executor: << parameters.go-version >>
    working_directory: ~/src/rolling-shutter
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          keys:
            - shuttermint-<< parameters.go-version >>-v8-{{ checksum "go.sum" }}
      - run: make build wasm
      - run:
          name: "Run tests with gotestsum"
          command: |
            mkdir report
            gotestsum -f standard-verbose --junitfile report/unit-tests.xml ./...
      - store_test_results:
          path: report
      - save_cache:
          key:
            shuttermint-<< parameters.go-version >>-v8-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"
            - "~/.cache/go-build"

  publish-release:
    executor: go
    working_directory: ~/src/rolling-shutter
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          keys:
            - shuttermint-go-v8-{{ checksum "go.sum" }}
      - run: env VERSION=${CIRCLE_TAG} ./build-release
      - run: go install github.com/tcnksm/ghr@v0.13.0
      - attach_workspace:
          at: ~/share
      - run:
          name: Upload binaries and combined.json
          command: |
            cp ~/share/combined.json bin/
            ghr ${CIRCLE_TAG} bin/

  rs-lint:
    executor: go
    working_directory: ~/src/rolling-shutter
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          keys:
            - lint-shuttermint-go-v7-{{ checksum "go.sum" }}
      - run:
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.40.1
      - run: |
          make lint-changes
      - save_cache:
          key: lint-shuttermint-go-v7-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"
            - "~/.cache/go-build"
            - "~/.cache/golangci-lint"
workflows:
  rolling-shutter:
    jobs:
      - rs-build:
          matrix:
            parameters:
              go-version: [go, go115, go116]
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-release:
          requires:
            - rs-build
          context:
            - upload-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - rs-lint:
          filters:
            branches:
              ignore: /main/
