# Shutter collator config
#
# Note: for snapshot shutter, we don't need to run a collator!
#
# Ethereum address: 0x2E135FE171fB6351026B75aF688a7F9689B66B87
# Peer identity: /p2p/12D3KooWFsVXBunDMNQZ8LLvS7BpY85Bop8isZaFAq6NVL7nLzUj

EthereumURL     = "http://geth:8545/"
ContractsURL    = "http://geth:8545/"
SequencerURL    = "http://geth:8545/"
DeploymentDir   = "./deployments/dockerGeth/"

# DatabaseURL looks like postgres://username:password@localhost:5432/database_name
# If it's empty, we use the standard PG* environment variables
DatabaseURL     = "postgres://postgres@db:5432/collator"

HTTPListenAddress = ":3000"

# p2p configuration
ListenAddresses   = ["/ip4/0.0.0.0/tcp/23000"]
CustomBootstrapAddresses  = [
    "/dns4/bootnode-0/tcp/23000/p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ",
    "/dns4/bootnode-1/tcp/23000/p2p/12D3KooWSayB2PEYpXtdk2dEqFaagoy8kDzmWpoD9DieuuzYdcBo"
]

# Secret Keys
EthereumKey     = "215ddd19b91c54252bb956c7f88e42122a61bd45a562d5bae38bc2328a9b52d0"
P2PKey          = "CAESQDTb6IrZcY37WUI2Ld42H4ixyA7S/7ttXBUt0J9EwuPGWfMtbuNarlScRbqIz6Dm8jZqZWkpECDx8r8PwXB97ZQ="

# ID shared by all shutter participants for common instance
InstanceID = 0

# The duration of an epoch
EpochDuration = "1s"

# Number of blocks to backdate batches
ExecutionBlockDelay = 5
