# Shutter keyper config
# Ethereum address: 0x312Ce8a364eF6785bBf47d612D1C4205E0Ba7243
# Peer identity: /p2p/12D3KooWLdS3Lzh5PQ7e3VP1LBr6X6V1vHJV5gxGHU4TzpN1KvQ4

ShuttermintURL		= "http://chain-0:26657"
EthereumURL         = "http://geth:8545/"
DeploymentDir       = "./deployments/dockerGeth/"

# DatabaseURL looks like postgres://username:password@localhost:5432/database_name
# If it's empty, we use the standard PG* environment variables
DatabaseURL		= "postgres://postgres@db:5432/keyper-0"
DKGPhaseLength		= 8

# p2p configuration
ListenAddresses   = ["/ip4/0.0.0.0/tcp/23000"]
CustomBootstrapAddresses  = [
    "/dns4/bootnode-0/tcp/23000/p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ",
    "/dns4/bootnode-1/tcp/23000/p2p/12D3KooWSayB2PEYpXtdk2dEqFaagoy8kDzmWpoD9DieuuzYdcBo"
]

# Secret Keys
EncryptionKey	= "10f6f94127e8df1728bd0fbabb97c74c4610e8fe70847e3fba4153b87f5f3e75"
SigningKey	= "8843a3df19ec3771f78607e4444614ed1b5918f80253f46555299d0d80b8c1f6"
ValidatorPublicKey	= "32e9b4b95033bb914250f708281b377b6cbbb62f60fc17ab51ee9bbf693d28c9"
P2PKey          = "CAESQOUbjXud1uTt6kAhYJ5ArQiKizbFMTA+yfZtX1wePkfYoKOLvbqdC7DSWEOd5ekZlACy1g5i6qM2KO79Q/NYWt0="

# HTTP interface
HTTPEnabled       = false
HTTPListenAddress = ":3000"

InstanceID = 0
