# Shutter snapshot config
# Ethereum address: 0xa8CC788afdAc07175cF05DbE0018cD19994DcD3b
# Peer identity: /p2p/12D3KooWHnFiZQmrMDYfyMJtrubcX4NhHvTgdbTTc5KmZLyKimhY
EthereumURL     = "http://geth:8545/"

# DatabaseURL looks like postgres://username:password@localhost:5432/database_name
# If it's empty, we use the standard PG* environment variables
DatabaseURL     = "postgres://postgres@db:5432/snapshot"

# Snapshot integration
#SnapshotHubURL       = "https://hub.snapshot.org/api/shutter"
SnapshotHubURL       = "http://dummyserver:5000"

# JSONRPC configuration
JSONRPCHost     = ""
JSONRPCPort     = 8754

# Metrics configuration
MetricsEnabled  = true
MetricsHost     = "0.0.0.0"
MetricsPort     = 9100

# p2p configuration
ListenAddresses	= ["/ip4/0.0.0.0/tcp/23000"]
CustomBootstrapAddresses  = [
    "/dns4/bootnode-0/tcp/23000/p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ",
    "/dns4/bootnode-1/tcp/23000/p2p/12D3KooWSayB2PEYpXtdk2dEqFaagoy8kDzmWpoD9DieuuzYdcBo"
]

# Secret Keys (we reuse the collator EthereumKey, so snapshot can be authorized against collator contract)
EthereumKey     = "215ddd19b91c54252bb956c7f88e42122a61bd45a562d5bae38bc2328a9b52d0"
P2PKey          = "CAESQHZ/uVq1ZWbbQkHVZqBnNwCsq+ygQTLBYogpcARCdBWkdlMKAnx2vuIZo3eAI+iK2KKTeuK7PsK1wO0fwF4bEKc="
